version: '2'
services:
    jbaptiste-app:
        image: jbaptiste
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://jbaptiste-mariadb:3306/jbaptiste
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jbaptiste-mariadb:
        extends:
            file: mariadb.yml
            service: jbaptiste-mariadb
